<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:31:13',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:40:50',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:33:38',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:33:29',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:33:17',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:40:50',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:40:50',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2024-10-18 00:40:50',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2024-10-17 22:28:27',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2024-10-18 00:33:05',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2024-12-08 20:33:25',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Administración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-regular fa-folder-open',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2025-02-09 23:42:49',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Clientes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 3,
                'created_at' => '2025-04-06 17:43:00',
                'updated_at' => '2025-12-07 19:24:39',
                'route' => 'voyager.people.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Bandejas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-inbox',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2025-11-30 23:25:51',
                'updated_at' => '2025-12-10 11:34:55',
                'route' => 'voyager.appointments.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Parámetro',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2025-11-30 23:27:13',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Especies',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paw',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2025-11-30 23:32:06',
                'updated_at' => '2025-12-02 00:33:29',
                'route' => 'voyager.animals.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Servicios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-stethoscope',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2025-11-30 23:48:02',
                'updated_at' => '2025-11-30 23:50:16',
                'route' => 'voyager.services.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Parámetro de Inventario',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2025-12-01 17:46:20',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Laboratorios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-microscope',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 4,
                'created_at' => '2025-12-01 18:15:33',
                'updated_at' => '2025-12-03 23:02:16',
                'route' => 'voyager.laboratories.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Marcas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-copyright',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 5,
                'created_at' => '2025-12-01 18:34:42',
                'updated_at' => '2025-12-03 23:02:16',
                'route' => 'voyager.brands.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Compras / Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-plus',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2025-12-01 18:39:56',
                'updated_at' => '2025-12-06 12:47:20',
                'route' => 'incomes.index',
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Proveedores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ship',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 3,
                'created_at' => '2025-12-01 18:51:18',
                'updated_at' => '2025-12-03 23:02:16',
                'route' => 'voyager.suppliers.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Productos / Items',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2025-12-01 19:13:15',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => 'voyager.items.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Mascotas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-dog',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2025-12-02 05:53:24',
                'updated_at' => '2025-12-10 11:26:28',
                'route' => 'voyager.pets.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Categorías',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-layer-group',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2025-12-03 22:57:21',
                'updated_at' => '2025-12-03 23:02:08',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Presentaciones / Unidad Medidas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2025-12-03 23:01:29',
                'updated_at' => '2025-12-03 23:02:16',
                'route' => 'voyager.presentations.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Trabajadores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-user-doctor',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 2,
                'created_at' => '2025-12-07 19:24:11',
                'updated_at' => '2025-12-07 19:24:39',
                'route' => 'voyager.workers.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Cajas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cash-register',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2025-12-10 11:26:08',
                'updated_at' => '2025-12-10 11:34:55',
                'route' => 'cashiers.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Ventas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-plus',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2025-12-10 11:35:18',
                'updated_at' => '2025-12-10 11:37:46',
                'route' => 'sales.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}